apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          command:
            - /usr/local/bin/etcd
            - --name
            - etcd
            - --initial-advertise-peer-urls
            - http://etcd:2380
            - --listen-peer-urls
            - http://0.0.0.0:2380
            - --listen-client-urls
            - http://0.0.0.0:2379
            - --advertise-client-urls
            - http://etcd:2379
            - --initial-cluster
            - etcd=http://etcd:2380
            - --initial-cluster-state
            - new
          image: quay.io/coreos/etcd:latest
          ports:
            - containerPort: 2379
              name: etcd
            - containerPort: 2380
              name: etcd1
