apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageserver-deployment
spec:
  selector:
    matchLabels:
      app: pageserver
  template:
    metadata:
      labels:
        app: pageserver
    spec:
      containers:
        - name: pageserver
          image: neondatabase/neon
          command:
            - pageserver
          ports:
            - name: http
              containerPort: 9898
            - containerPort: 6400
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
