apiVersion: apps/v1
kind: Deployment
metadata:
  name: safekeeper-deployment
spec:
  selector:
    matchLabels:
      app: safekeeper
  template:
    metadata:
      labels:
        app: safekeeper
    spec:
      containers:
        - name: safekeeper
          image: neondatabase/neon
          command:
            - safekeeper
          args:
            - --id # What is ID for?
            - "1"
            - -l
            - "0.0.0.0:5454"
            - --listen-http
            - "0.0.0.0:7676"
            - "--pageserver"
            - "pageserver:6400"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"

          ports:
            - containerPort: 5454
            - containerPort: 7676
